# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'byebug', '~> 11.0'
gem 'rspec', '~> 3.8'
gem 'rubocop', '~> 0.65.0'
